-- AlterTable
ALTER TABLE "WatchlistItem" ADD COLUMN "targetBuyPrice" DOUBLE PRECISION,
ADD COLUMN "targetAllocPct" DOUBLE PRECISION,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
